version: '3.8'

services:
  bot:
    build: .
    container_name: mecha_bot
    restart: always
    volumes:
      - .:/app
      - /app/__pycache__
    env_file:
      - .env
    command: python main.py